# Numpy Data Type:

1. bool_
2. int_
3. int

In [16]:
import numpy as np 

empty=np.empty(4)
print(empty)

print(empty.dtype)


[6.01346953e-154 2.52760136e-258 4.47593804e-091 6.01346953e-154]
float64


In [17]:
array=np.array([1,2,4,5])
print(array.dtype)

int32


In [18]:
array1=np.array(["a",'b','c','d','e','f'])
print(array1.dtype) #String

<U1


In [19]:
array2=np.array(["a","b",1,2,3,4])
print(array2.dtype) #integer + String

<U11


# Type casting in numpy:

In [20]:
# Method 1

x1=np.array([1,2,3,4], dtype=np.float32)
print(x1.dtype)    

float32


In [21]:
# Method 2

x2=np.array([1,2,3,4], dtype='f')
print(x2.dtype)    

float32


In [22]:
# Method 3 
 
x3=np.array([1,2,3,4,5,6,7])
print(x3.dtype)

new_datatype=np.float32(x3)
print(new_datatype.dtype)

int32
float32


In [23]:
# Method 4

A = np.array([11,33,55,77,99])

New_A = A.astype(float)
 
print(A)
print(New_A)

[11 33 55 77 99]
[11. 33. 55. 77. 99.]


# Shape and Reshaping in nupy array:



In [26]:
array=np.array([[1,2,3],[1,2,3]])
print(array)
print(array.shape)

print()


array_1=np.array([[1],[1]])
print(array_1)
print(array_1.shape)

array_2=np.array([1,2,3,4],ndmin=3)
print(array_2)
print(array_2.ndim)
print(array_2.shape)

array_3=np.array([[[1,2,3],[4,5,6]]])
print(array.ndim)


[[1 2 3]
 [1 2 3]]
(2, 3)

[[1]
 [1]]
(2, 1)
[[[1 2 3 4]]]
3
(1, 1, 4)
2


In [16]:
x="H1E21L3L4O5"
#x1 = int(string) 
y=list(x)
z=[]

#print(type(string))
print(type(x))


print(ord(y[0]))

print(ord(y[1]))

print (y)
print(type(y[1]))

for i in y:
    if ord(i)>=49 and ord(i)<=57:
        if i and i+1 == 49<=ord(i)<=57:
               
        z.append(int(A))

sum=0


for i in z:
    sum=sum+i
    
print(sum)



<class 'str'>
72
49
['H', '1', 'E', '2', '1', 'L', '3', 'L', '4', 'O', '5']
<class 'str'>


TypeError: can only concatenate str (not "int") to str

In [13]:
x=[21,20]
print(ord(x[1]))

TypeError: ord() expected string of length 1, but int found

# 

# Arithmetic Operations:- 

1. a+b   OR   np.add(a,b)
2. a-b   OR   np.subtract(a,b)
3. a*b   OR   np.multipy(a,b)
4. a/b   
5. a%b
6. a**b
7. 1/a

In [3]:
import numpy as np 

var = np.array([1,2,3,4])

varadd = var + 3 
print(varadd)

[4 5 6 7]


In [4]:
A = np.array([1,2,3,4])
print(A.dtype)
B = A*3
B
print(B)

print()

C=A/2
print(C)

print(C.dtype)

int32
[ 3  6  9 12]

[0.5 1.  1.5 2. ]
float64


In [5]:
x= np.array([1,2,3])
y=np.array([2,3,4])
z=x*y
print(z)
print(z.dtype)

print()

Q1=np.add(x,y)
print(Q1)

print()

Q2=np.multiply(x,y)
print(Q2)

print()

Q3=np.power(x,y)
print(Q3)

[ 2  6 12]
int32

[3 5 7]

[ 2  6 12]

[ 1  8 81]


In [11]:
x= np.array([1,2,3])
y=np.array([2,3,4])

a1=np.min(x)
print(a1)

a2=np.max(y)
a2

a3=np.argmin(y)
a3

print("heloooo")
a4=np.sqrt(x)
a4


1
heloooo


array([1.        , 1.41421356, 1.73205081])