In [2]:
import numpy as np 

In [3]:
list =[1,2,3,6]
print(list)
print(type(list))

[1, 2, 3, 6]
<class 'list'>


In [4]:
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))
#ndArray= n-dimentional array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


Numpy Array V/S List:-

1. In List data of multiple data type can be stored at a time, While in array 
   it only data type need to be selected to perform mathematical calculation.
2. For List no module need to be installed while for numpy module need to be      insatlled.
3. USing List heavy numerical problem(MATRIX OPERATON) cannot be perform,          while numpy is able to perform.
4. More modification option are avialable in list, it is not in array.
5. Numpy Array consume less memory in compare to list.
6. Numpy array is much faster than python list.

In [5]:
%%timeit
x=np.array([1,2,3,6])
for i in x:
    print(i)

1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6


1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2


In [6]:
%%timeit
list =[1,2,3,6]
for i in list:
    print(i)
#[for i in list]

1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6


2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6


2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1


2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1


1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6


6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3
6
1
2
3


ARRAY:-

In [8]:
a=[1,2,3,4,5] #list
c=(1,2,3,4,5,6,7,8) #tuple
b=np.array(c) #converting list and tuple into numpy array
d=np.array(a)
print(b,d)

[1 2 3 4 5 6 7 8] [1 2 3 4 5]


In [9]:
L=[]


for i in range(1,5):
    x=int(input("Enter value:"))
    L.append(x)
print(L)
a=np.array(L)
print(a)
print(type(a))
print(type(L))

Enter value:1
Enter value:2
Enter value:3
Enter value:4
[1, 2, 3, 4]
[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


Types of Array :-
1. 1-D
2. 2-D
3. 3-D
4. Higher Dimentional

In [53]:
y=np.array([9,8,7,6,5])
print(y)
print(y.ndim)

[9 8 7 6 5]
1


In [47]:
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
print(z.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [48]:
z=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(z)
print(z.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [50]:
z=np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(z)
print(z.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]
4


In [52]:
# shortcut of creating n dimentional array using "ndmin"

a=np.array([1,2,3],ndmin=10)
print(a)
print(a.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10


# Creating Numpy array using function :  
1. zero's array.
2. one's array.
3. Empty array.
4. array with range of element.
5. Diagonal element filled with 1's.
6. Create array with values that are spaced linearly

ZEROS:

In [69]:
zero_array=np.zeros(3)
print(zero_array)
print ()
zero_array1=np.zeros((3, 4))
print(zero_array1)

[0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones:

In [3]:
ones_array=np.ones(3)
print(ones_array)
print ()
ones_array1=np.ones((3, 4))
print(ones_array1)

[1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Empty:

In [70]:
empty_array=np.empty(3)
print(empty_array)

# The output of this function will depend on the previous array created,
# It will take values from previously created array
# If there is no previous array default it will take zero's value

[0. 0. 0.]


Range:

In [71]:
range_array=np.arange(5)
print(range_array)

[0 1 2 3 4]


Diagonal:

In [76]:
diagonal_array=np.eye(3)
print(diagonal_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [75]:
diagonal_array=np.eye(3,5)
print(diagonal_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


Linespace:

In [86]:
line_array=np.linspace(0,20,num=5)
print(line_array)

[ 0.  5. 10. 15. 20.]


# Creating numpy array with random numbers:

1. rand() : It will create a 1-d array with number between 0 & 1
2. randn(): It will crate create array of value close to zero, values may be 
            +ve or -ve.
3. randf() : It fills random number between range [0.0, 1.0).
4. randint():It will genrate values in array between given range.

In [88]:
# 1. 
ran=np.random.rand(5)
print(ran)

[0.41802764 0.33700577 0.16004929 0.61495583 0.42930348]


In [91]:
# 2. 
ran_n=np.random.randn(5)
print(ran_n)

[ 2.22434172 -1.05381891 -0.18423907 -0.23868651  0.50003509]


In [95]:
# 3.
ran_f=np.random.ranf(4)
print(ran_f)


[0.65242437 0.30496267 0.05798508 0.92652347]


In [99]:
# 4. 
# ran_int=np.random.randint(min, max, number of elements)

rand_int=np.random.randint(1,6,4)
print(rand_int)


[5 4 1 3]
