# # Types of Numpy Matrix

In [2]:
import numpy as np

Array:- np.array

In [3]:
List=[1,2,3,4,5]
print(List)

[1, 2, 3, 4, 5]


In [4]:

l=[1,2,3,4,5]
array=np.array([List])
print(array)

[[1 2 3 4 5]]


Identity Matrix :- np.eye()

In [5]:
ar= np.eye(3)
print(ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
array=np.eye(100,100)
print(array)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Ones:- np.ones()

In [6]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


Empty:- np.empty()

In [7]:
#Empty_Array = np.empty(3)
Empty_Array = np.empty([3,2],dtype=int)
print(Empty_Array)

[[         0 1072693248]
 [         0 1072693248]
 [         0 1072693248]]


In [24]:
List=[1,5,3,4,2]
array=np.array([List])
print(array)
arranged_array=np.sort(array)
print(arranged_array)

[[1 5 3 4 2]]
[[1 2 3 4 5]]


Arrange function:- np.arrange()

In [27]:
A=np.arange(1,10,1)
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
